---

- hosts: all
  become: true
  tasks:

# The first plays are for Ubuntu

  - name: Install Apache, PHP support and Htop
    apt:
      update_cache: yes
      name: 
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when: ansible_distribution == "Ubuntu"

# The following plays are for Rocky Linux

  - name: Install Apache, PHP support and Htop
    dnf:
      update_cache: yes
      name:
        - httpd
        - php
        - htop
      state: latest
    when: ansible_distribution == "Rocky"
